### ISSUE TITLE
`<module:Constants>': uninitialized constant Creek::Styles::Constants::Date (NameError)

### ISSUE THREAD

**Issue by reaper** [pythonicrubyist/creek#14]
Require the lib raise a uninitialized constant exception with ruby 2.2.0:

```
/home/reaper/.rvm/gems/ruby-2.2.0/gems/creek-1.0.6/lib/creek/styles/constants.rb:40:in `<module:Constants>': uninitialized constant Creek::Styles::Constants::Date (NameError)
        from /home/reaper/.rvm/gems/ruby-2.2.0/gems/creek-1.0.6/lib/creek/styles/constants.rb:3:in `<class:Styles>'
        from /home/reaper/.rvm/gems/ruby-2.2.0/gems/creek-1.0.6/lib/creek/styles/constants.rb:2:in `<module:Creek>'
        from /home/reaper/.rvm/gems/ruby-2.2.0/gems/creek-1.0.6/lib/creek/styles/constants.rb:1:in `<top (required)>'
        from /home/reaper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/reaper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/reaper/.rvm/gems/ruby-2.2.0/gems/creek-1.0.6/lib/creek.rb:3:in `<top (required)>'
        from /home/reaper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /home/reaper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /home/reaper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from ./import_excel.rb:3:in `<main>'
```

**Comment by pythonicrubyist** [comment]
Can you please provide me the Excel file that you are trying to parse and also the code you are using to parse, so that I can trouble shoot this error?

**Comment by reaper** [comment]
No excel file was provided, just the require call raised the exception.

**Comment by pythonicrubyist** [comment]
The problem should be fixed now. Please update the gem to the latest version 1.0.8 and it should work fine!
Thanks for reporting the bug and please let me know if you face any other problem.
